### ISSUE TITLE
How is the score in the final ranking calculated

### ISSUE THREAD

**Issue by P2Oileen** [dc3ea9f/vico_challenge_baseline#3]
Thank you for nice repo and Vico challenge.
The [website](https://vico-challenge.github.io/) mentioned that the quality of generated videos will be quantitative evaluated from serveral prespectives, and scripts are provided.
How will you combine these scores, for example, is the final score a weighted sum of these metrics, or in some other ways?

**Comment by wyvernbai** [comment]
> Thank you for nice repo and Vico challenge. The [website](https://vico-challenge.github.io/) mentioned that the quality of generated videos will be quantitative evaluated from serveral prespectives, and scripts are provided. How will you combine these scores, for example, is the final score a weighted sum of these metrics, or in some other ways?

First of all, all scores of these metrics will be listed on the final leaderboard. However, since there is no reference work about how to set the weights for all these different metrics, we rank the submissions according to the **amount of the Top-1**. It means the team whose generated videos achieved the most Top-1 results among all metrics will get the first place.
